-- AlterTable
ALTER TABLE "Clan" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "ClanInfoGameType" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "ClanInfoMap" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "ClanPlayerInfo" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "GameType" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Map" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PlayerInfoGameType" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PlayerInfoMap" ALTER COLUMN "playTime" SET DATA TYPE BIGINT;
