services:
  # Hide logs from the database because they are not useful and only add noises.

  database-test:
    image: "redis:6"
    ports:
      - "6379:6379"
    logging:
      driver: none

  # The test container uses pytest-watch to run tests as soon as a file changes.
  # Bind host folders to the container so tha tpytest-watch can work properly.

  test:
    build:
      dockerfile: test/Dockerfile
    depends_on:
      - database-test
    environment:
      - TEERANK_REDIS_HOST=database-test
    volumes:
      - ./frontend:/usr/src/app/frontend:ro
      - ./backend:/usr/src/app/backend:ro
      - ./shared:/usr/src/app/shared:ro
      - ./test:/usr/src/app/test:ro
