services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      target: production
    ports:
      - "80:8080"

  backend:
    build:
      dockerfile: backend/Dockerfile
      target: production
    depends_on:
      - redis
    ports:
      - "8311:8311/udp"

  redis:
    image: redis:6
