services:
  test:
    build:
      dockerfile: test/Dockerfile
    depends_on:
      - database-test
    environment:
      - TEERANK_REDIS_HOST=database-test

  database-test:
    image: "redis:6"
    ports:
      - "6379:6379"
