services:
  # Hide redis database logs because they don't provides useful development
  # information.

  database-test:
    image: "redis:6"
    logging:
      driver: none

  # The test container uses pytest-watch to run tests as soon as a file changes.
  # Bind host folders to the container so that pytest-watch can work properly.

  test:
    build:
      dockerfile: test/Dockerfile
    depends_on:
      - database-test
    environment:
      - TEERANK_REDIS_HOST=database-test
    volumes:
      - ./frontend:/usr/src/app/frontend:ro
      - ./backend:/usr/src/app/backend:ro
      - ./shared:/usr/src/app/shared:ro
      - ./test:/usr/src/app/test:ro
