version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teerank
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: always

  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: postgres-test
      POSTGRES_DB: teerank-test
    ports:
      - "5433:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis
