services:
  # Hide redis database logs because they don't provides useful development
  # information.

  database:
    image: "redis:6"
    logging:
      driver: none

  # Bind host source files to the container so that it can be restarted when
  # they change.

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      target: development
    depends_on:
      - database
    volumes:
      - ./frontend:/usr/src/app/frontend:ro
      - ./shared:/usr/src/app/shared:ro
    ports:
      - "80:5000"

  # Bind host source files to the container so that it can be restarted when
  # they change.

  backend:
    build:
      dockerfile: backend/Dockerfile
      target: development
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app/backend:ro
      - ./shared:/usr/src/app/shared:ro
    ports:
      - "8311:8311/udp"
