# fly.toml app configuration file generated for teerankio-scheduler on 2024-11-30T05:12:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teerankio-scheduler'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
