# fly.toml app configuration file generated for teerankio-search on 2024-11-25T04:11:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teerankio-search'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512

[mounts]
  source = "teerankio_search_data"
  destination = "/data"
