-- AlterTable
ALTER TABLE "GameType" ADD COLUMN     "clanCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "countedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "gameServerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mapCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "playerCount" INTEGER NOT NULL DEFAULT 0;
