name: CI
on:
  push:
    branches:
      - rework
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres-test
          POSTGRES_PASSWORD: postgres-test
          POSTGRES_DB: teerank-test
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run-many -t lint --parallel=3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Migrate database
        run: |
          flyctl proxy 5434:5432 --app teerankio-postgres &
          npx nx run-many -t prisma-generate --parallel=3
          npx nx run-many -t prisma-deploy --parallel=3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_POSTGRES }}

      - name: Build
        run: npx nx run-many -t build --parallel=3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Test
        run: |
          npx nx run prisma:prisma-push
          npx nx run-many -t test --runInBand
        env:
          DATABASE_URL: postgres://postgres-test:postgres-test@localhost:5433/teerank-test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy frontend
        run: flyctl deploy --config apps/frontend/fly.toml --dockerfile apps/frontend/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}

  deploy-scheduler:
    name: Deploy scheduler
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy scheduler
        run: flyctl deploy --config apps/scheduler/fly.toml --dockerfile apps/scheduler/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_SCHEDULER }}

  deploy-worker:
    name: Deploy worker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy worker
        run: flyctl deploy --config apps/worker/fly.toml --dockerfile apps/worker/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_WORKER }}
