name: CI
on:
  push:
    branches:
      - rework
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run-many -t lint --parallel=3

      - name: Prisma Generate
        run: npx nx run-many -t prisma-generate --parallel=3

      - name: Build
        run: npx nx run-many -t build --parallel=3

      - name: Test
        run: npx nx run-many -t test --parallel=3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          tags: s0laster/teerank.io-frontend:latest
          push: true

      - name: Docker push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          tags: s0laster/teerank.io-backend:latest
          push: true

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy frontend
        run: flyctl deploy apps/frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}

      - name: Deploy backend
        run: flyctl deploy apps/backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}

      - name: Migrate database
        run: npx nx run-many -t prisma-deploy --parallel=3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
