name: CI
on:
  push:
    branches:
      - rework
  pull_request:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run-many -t lint --parallel=3

      - name: Prisma Generate
        run: npx nx run-many -t prisma-generate --parallel=3

      - name: Build
        run: npx nx run-many -t build --parallel=3

      - name: Test
        run: npx nx run-many -t test --parallel=3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          tags: s0laster/teerank.io-frontend:latest
          push: true

      - name: Docker push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          tags: s0laster/teerank.io-backend:latest
          push: true

      - name: Migrate database
        run: npx nx run-many -t prisma-deploy --parallel=3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy frontend
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: teerank.io
          containerAppName: frontend
          imageToDeploy: registry.hub.docker.com/s0laster/teerank.io-frontend:latest
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}

  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy frontend
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: teerank.io
          containerAppName: frontend
          imageToDeploy: registry.hub.docker.com/s0laster/teerank.io-frontend:latest
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
