import Image from 'next/image';
import './global.css';
import { twMerge } from 'tailwind-merge';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

function Tab({
  label,
  sublabel,
  sublabelPlaceholder,
  isActive,
}: {
  label: string;
  sublabel?: string;
  sublabelPlaceholder?: string;
  isActive: boolean;
}) {
  return (
    <div
      className={twMerge(
        'flex flex-row divide-x py-1.5 rounded-t-md border border-[#dddddd] border-b-0 text-base divide-[#999]',
        isActive
          ? 'bg-white'
          : 'bg-gradient-to-b from-[#ffffff] to-[#cccccc] cursor-pointer'
      )}
    >
      <span className="px-4">{label}</span>
      {sublabel !== undefined && <span className="px-4">{sublabel}</span>}
      {sublabel === undefined && sublabelPlaceholder !== undefined && (
        <span className="px-4 italic">{sublabelPlaceholder}</span>
      )}
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[url('/background.png')] bg-repeat-x bg-left-top flex flex-col items-center m-0 bg-[#9EB5D6] text-[#666]">
        <header className="max-w-5xl w-full flex flex-row py-4">
          <Image src="/logo.png" alt="Logo" width={483} height={98} />
        </header>

        <main className="max-w-5xl w-full rounded-xl bg-[#e7e5be] shadow-sm">
          <header className="flex flex-row gap-2 -mt-1.5 px-8">
            <Tab label="Home" isActive={false} />
            <Tab label="CTF" isActive={true} sublabelPlaceholder="All maps" />
            <Tab label="DM" isActive={false} />
            <Tab label="..." isActive={false} />
            <div className="grow" />
            <Tab label="About" isActive={false} />
          </header>

          <main className="bg-white rounded-xl shadow-md">{children}</main>
        </main>

        <footer className="flex flex-row gap-6 items-center py-8 text-sm text-white">
          <Link
            href="/"
            className="[text-shadow:_1px_1px_1px_#383838] hover:underline"
          >
            Teerank 1.0 (stable)
          </Link>
          <Link
            href="/"
            className="[text-shadow:_1px_1px_1px_#383838] hover:underline"
          >
            Status
          </Link>
          <Link
            href="/"
            className="[text-shadow:_1px_1px_1px_#383838] hover:underline"
          >
            About
          </Link>
        </footer>
      </body>
    </html>
  );
}
